### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by SidJain1412** [rsamit26/InterviewBit#1]
https://github.com/rsamit26/InterviewBit/blob/6792fa4f8f6d2c84df18cd4312a999d80d254bb3/Python/Arrays/ArrayMath/Add%20One%20To%20Number.py#L9-L18

This will work for barely any testcases. 
Example: `9,9,9` should give `1,0,0,0` not `9,9,10`

**Comment by rsamit26** [comment]
@SidJain1412 Have you checked the output for [9,9,9]. I think this will work properly and give the correct output that is [1, 0, 0, 0]
Thanks.
